ignore:
  - "src/main/scala/testgrid.worksheet.sc"
  - "src/main/scala/de/htwg/se/minesweeper/Minesweeper.scala"
  - "src/main/scala/de/htwg/se/minesweeper/views/gui/SwingGui.scala"
  - "src/main/scala/de/htwg/se/minesweeper/views/gui/Test.scala"
  - "src/main/scala/de/htwg/se/minesweeper/views/gui/Gui.scala"
