ignore:
  - "src/main/scala/testgrid.worksheet.sc"
  - "src/main/scala/de/htwg/se/minesweeper/Minesweeper.scala"
  - "src/main/scala/de/htwg/se/minesweeper/views"
  - "src/main/scala/de/htwg/se/minesweeper/model/fileIO"
  - "src/main/scala/de/htwg/se/minesweeper/controller/modules"
