name: Scala Coveralls

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_java_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Project
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          export CI_BRANCH="${GITHUB_REF#refs/heads/}"
          sbt clean jacoco jacocoCoveralls
